#!/bin/bash
FILE_PATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
ROOT_PATH=`dirname $FILE_PATH`
BINDIR="$ROOT_PATH/bin"
. $BINDIR/utils/constants.sh

$CONDA create -y --prefix=$FILE_PATH/env python=3.13
$ACTIVATE $FILE_PATH/env
$CONDA install -p $FILE_PATH/env -y numpy
$FILE_PATH/env/bin/pip install ldpc